<script type="text/javascript" src="../../files/js/jquery.min.js"></script>
            <script type="text/javascript" src="../../files/js/bootstrap.min.js"></script>
            <script type="text/javascript" src="../../files/js/Chart.min.js"></script>
            <script type="text/javascript" src="../../files/js/bootstrap-switch.min.js"></script>
            <script type="text/javascript" src="../../files/js/jquery.matchHeight-min.js"></script>
            <script type="text/javascript" src="../../files/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript" src="../../files/js/dataTables.bootstrap.min.js"></script>
            <script type="text/javascript" src="../../files/js/select2.full.min.js"></script>
            <script type="text/javascript" src="../../files/js/ace/ace.js"></script>
            <script type="text/javascript" src="../../files/js/ace/mode-html.js"></script>
            <script type="text/javascript" src="../../files/js/ace/theme-github.js"></script>
            <!-- Javascript -->
            <script type="text/javascript" src="../../files/js/app.js"></script>
            <script type="text/javascript" src="../../files/js/index.js"></script>